# https://github.com/VladCroitoru/dockerfile_smells_project/blob/main/gha_dockerfiles/soootaleb/abcd/Dockerfile

FROM denoland/deno:alpine AS build

WORKDIR /opt/app

COPY . .

RUN deno compile \
    --unstable \
    --allow-all \
    --target x86_64-unknown-linux-gnu \
    --output server \
    ./server.ts

# FROM scratch AS runtime

# WORKDIR /opt/app

# # get dynamicly linked dependencies
# COPY --from=dabian /usr/lib/x86_64-linux-gnu/libnss_dns.so.2 /lib/
# COPY --from=dabian /usr/lib/x86_64-linux-gnu/libresolv.so.2 /lib/

# COPY --from=dabian /lib/x86_64-linux-gnu/libdl.so.2 /lib/
# COPY --from=dabian /lib/x86_64-linux-gnu/libstdc++.so.6 /lib/
# COPY --from=dabian /lib/x86_64-linux-gnu/libgcc_s.so.1 /lib/
# COPY --from=dabian /lib/x86_64-linux-gnu/librt.so.1 /lib/
# COPY --from=dabian /lib/x86_64-linux-gnu/libpthread.so.0 /lib/
# COPY --from=dabian /lib/x86_64-linux-gnu/libm.so.6 /lib/
# COPY --from=dabian /lib/x86_64-linux-gnu/libc.so.6 /lib/
# COPY --from=dabian /lib64/ld-linux-x86-64.so.2 /lib64/

# COPY --from=build --chmod=0755 /opt/app/server /opt/app/server

# EXPOSE 3000

# CMD ["/opt/app/server"]

FROM gcr.io/distroless/static-debian12:nonroot AS runtime

COPY --from=build --chmod=0755 /opt/app/server /opt/app/server

EXPOSE 3000

WORKDIR /opt/app

CMD ["/opt/app/server"]
