# https://github.com/VladCroitoru/dockerfile_smells_project/blob/main/gha_dockerfiles/soootaleb/abcd/Dockerfile
FROM ubuntu as deps

FROM oven/bun:alpine AS build

WORKDIR /opt/app

COPY . .

RUN bun build \
	--compile \
	--target=bun-linux-x64 \
	--outfile server\
	./server.ts

FROM scratch AS runtime

WORKDIR /opt/app

# get dynamicly linked dependencies
COPY --from=deps /usr/lib/x86_64-linux-gnu/libnss_dns.so.2 /lib/
COPY --from=deps /usr/lib/x86_64-linux-gnu/libresolv.so.2 /lib/

COPY --from=deps /lib/x86_64-linux-gnu/libdl.so.2 /lib/
COPY --from=deps /lib/x86_64-linux-gnu/libstdc++.so.6 /lib/
COPY --from=deps /lib/x86_64-linux-gnu/libgcc_s.so.1 /lib/
COPY --from=deps /lib/x86_64-linux-gnu/librt.so.1 /lib/
COPY --from=deps /lib/x86_64-linux-gnu/libpthread.so.0 /lib/
COPY --from=deps /lib/x86_64-linux-gnu/libm.so.6 /lib/
COPY --from=deps /lib/x86_64-linux-gnu/libc.so.6 /lib/
COPY --from=deps /lib64/ld-linux-x86-64.so.2 /lib64/

COPY --from=build --chmod=0755 /opt/app/server /opt/app/server

EXPOSE 3000

CMD ["/opt/app/server"]
